name: Capture API Metrics

on:
  schedule:
    - cron: '0 */6 * * *'  # Set the schedule based on your needs, this example runs every 6 hours

jobs:
  capture_metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set the desired Python version

    - name: Execute capture_metrics.sh
      run: |
        ./capture_metrics.sh >> api_metrics.log  # Replace with the actual command to capture metrics

    - name: Commit and push changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add api_metrics.log
        git commit -m "Update API metrics [skip ci]"
        git push
